version: "3"
services:
  app:
    container_name: app-springboot
    image: alaanescobedo/app-springboot
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - postgres
    links:
      - postgres:postgres
    env_file:
      - docker.env

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8081:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge