import Head from 'next/head'
import { Text } from '@chakra-ui/react'
import { GetStaticPaths, GetStaticProps, GetStaticPropsContext } from 'next'

interface UserProfileProps {
  username: string
}
export default function UserProfile({ username }: UserProfileProps) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Text>
          This is the profile page for {username}
        </Text>
      </main>


    </div>
  )
}

// getStaticPaths
export const getStaticPaths: GetStaticPaths = async () => {

  const username = 'JohnDoe'

  return {
    paths: [
      { params: { username } }
    ],
    fallback: false
  }
}

//getStaticProps
export const getStaticProps: GetStaticProps = async ({ params }: GetStaticPropsContext) => {
  const username = params?.username as string

  if (!username) return {
    notFound: true,
    redirect: '/',
  }

  return {
    props: {
      username
    }
  }
}