import { Heading } from '@chakra-ui/react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <Heading>
          404 - Page Not Found
        </Heading>

      </main>


    </div>
  )
}

export default Home
