import { Box, Container, Flex, Grid, GridItem, Spinner } from '@chakra-ui/react'
import Head from 'next/head'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import UserCard from '../src/components/user-card'
import usersService from '../src/services/users.service'

export default function Home() {

  const query = useQuery({
    queryKey: ['users_profile'], queryFn: async () => {
      return usersService.getUsersPublicProfile()
    },
    refetchOnWindowFocus: false,
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW={'container.lg'}>
        <Box as='main' flex='1' >

          {query.isError && <p>Error</p>}
          <Grid templateColumns='repeat(auto-fill, minmax(300px, 1fr))' gap={4} textAlign="center">
            {query.isLoading && (
              Array.from({ length: 9 }).map((_, index) => (
                <GridItem key={index} py={'28'}>
                  < Spinner />
                </GridItem>
              ))
            )}
            {query.isSuccess && query.data.map((user) => (
              <GridItem key={user.id}>
                <UserCard user={user} />
              </GridItem>
            ))}
          </Grid>
        </Box>
      </Container>
    </>
  )
}
