import { Box, Container, Flex, Grid, GridItem, Spinner } from '@chakra-ui/react'
import Head from 'next/head'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import UserCard from '../src/components/user-card'
import usersService from '../src/services/users.service'
import { RenderIf } from '../src/components/render-if'
import { User } from '../src/store'
import { useState, useEffect } from 'react'

export default function Home() {

  const query = useQuery({
    queryKey: ['users_profile'], queryFn: async () => {
      return usersService.getUsersPublicProfile()
    },
    refetchOnWindowFocus: false,
  })

  const [usersData, setUsersData] = useState<User[]>(query.data || [])

  useEffect(() => {
    if (query.isSuccess) setUsersData(query.data)
  }, [query.isFetched])


  return (
    <>
      <Head>
        <title>My files</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW={'container.lg'}>
        <Box as='main' flex='1' >

          <RenderIf condition={query.isError}>
            <p>Error</p>
          </RenderIf>

          <Grid templateColumns='repeat(auto-fill, minmax(300px, 1fr))' gap={4} textAlign="center">
            <RenderIf condition={query.isError}>
              <p>Error</p>
            </RenderIf>
            <RenderIf condition={query.isLoading}>
              {Array.from({ length: 9 }).map((_, index) => (
                <GridItem key={index} py={'28'}>
                  < Spinner />
                </GridItem>
              ))}
            </RenderIf>

            <RenderIf condition={query.isSuccess && usersData.length > 0}>
              {usersData.slice(0).reverse().map((user) => (
                <GridItem key={user.id}>
                  <UserCard user={user} />
                </GridItem>
              ))}
            </RenderIf>
          </Grid>
        </Box>
      </Container>
    </>
  )
}
