import { Box, Container, Flex, Grid, GridItem, Spinner } from '@chakra-ui/react'
import Head from 'next/head'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import UserCard from '../src/components/user-card'
import usersService from '../src/services/users.service'
import { RenderIf } from '../src/components/render-if'
import { User, useUser } from '../src/store'
import { useState, useEffect } from 'react'
import { GetStaticProps } from 'next'
import { useRouter } from 'next/router'

export default function Home({ profiles }: { profiles: User[] }) {
  const { user: myUser } = useUser()

  return (
    <>
      <Head>
        <title>My files</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW={'container.lg'}>
        <Box as='main' flex='1' >

          <Grid templateColumns='repeat(auto-fill, minmax(300px, 1fr))' gap={4} textAlign="center">
            <RenderIf condition={myUser !== null}>
              <GridItem >
                <UserCard user={myUser!} />
              </GridItem>
            </RenderIf>
            {profiles.map((user) => {
              if (myUser?.id === user.id) return null
              return (
                <GridItem key={user.id}>
                  <UserCard user={user} />
                </GridItem>
              )
            })}
          </Grid>
        </Box>
      </Container>
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {

  const profiles = await usersService.getUsersPublicProfile()

  return {
    props: {
      profiles: profiles.slice(0).reverse()
    },
    revalidate: 1
  }
}
